sudo: false
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm
  - hhvm-nightly
branches:
  only:
    - master
cache:
  directories:
    - vendor
before_script:
  - composer self-update
  - composer install --prefer-source
script:
  - phpunit

# This part is there until Travis migrate to Ubuntu Trusty
# see: https://github.com/travis-ci/travis-ci/issues/3788
matrix:
  allow_failures:
    - php: hhvm-nightly
  fast_finish: true
